remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Programo m Dev
description: This is a coding patterns and tutorials website.
favicon: /favicon.ico

# Force footer inclusion
defaults:
  - scope:
      path: ""
    values:
      layout: default
