remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
favicon: /favicon.ico
# Force layout and footer inclusion
layout: default  # Ensures full theme layout
exclude:
  - .gitignore
  - README.md
